name: beflax
favicon: null
layout_spectrum: 0.21163964201696217
typography_spectrum: 0.8736580987460911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#99cffe'
    - '#ffffff'
    - '#090e17'
    - '#5c606a'
    - '#919397'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.333062608493492
purpose: []
