name: Beflax - Natural Linen Textile
favicon: null
layout_spectrum: 1
typography_spectrum: 0.84715
title: The Gift of Nature in your Home
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#64a1d7'
    - '#0c0e16'
    - '#cacacf'
    - '#646675'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
