name: beflax
favicon: null
layout_spectrum: 0.21163964201696217
typography_spectrum: 0.8736580987460911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.09800927015021443
  lightness: 0.3102170981001109
  saturation: 0.13457453553564847
  rhythmicContrast: 0.333062608493492
purpose: []
